### ISSUE TITLE
Codebook todo

### ISSUE THREAD

**Issue by gurnoor1990** [fairgenomes/information#104]
- [x] Update  Hl7 codes
- [x] Add  Hl7 codes to all list
- [ ] Make Biocompare ontology and add code list id (Idea dropped for the current version of codebook, we first release and develop an ontology later )
- [x] Check format standardization
- [ ] AGB-code (Hospital codes) (Idea dropped)

**Comment by gurnoor1990** [comment]
-DUOrestricted list

**Comment by aderidder** [comment]
For the NULL-values:
https://decor.nictiz.nl/medicatieproces/mp-html-20160602T152837/voc-2.16.840.1.113883.1.11.10609-2011-07-26T000000.html

**Comment by gurnoor1990** [comment]
@aderidder 

Hi Sander, 

We have the same list in the FAIRgenomes codebook, but different codes. We are using, https://bioportal.bioontology.org/ontologies/HL7 ontology. 

Do you think that this code system is ok? In the Waardelijst NullFlavor 2011‑07‑26, codes are represented by spaces. I think we can use these codes based on the HL7 ontology

Thanks!
Gurnoor




| value_en                                  | description_en          | codesystem | code     | description_code                                                                                                                                                                                                                                                                                     |
|-------------------------------------------|-------------------------|------------|----------|------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| NullFlavor                                | NoInformation           | HL7        | C1553727 | The value is exceptional (missing, omitted, incomplete, improper). No information as to the reason for being an exceptional value is provided. This is the most general exceptional value. It is also the default exceptional value.                                                                 |
| Invalid (INV, nullflavor)                 | invalid                 | HL7        | C3245471 | The value as represented in the instance is not a member of the set of permitted data values in the constrained value domain of a variable.                                                                                                                                                          |
| Derived (DER, nullflavor)                 | derived                 | HL7        | C3245521 | An actual value may exist, but it must be derived from the provided information (usually an EXPR generic data type extension will be used to convey the derivation expressionexpression .                                                                                                            |
| Other (OTH, nullflavor)                   | other                   | HL7        | C1556044 | The actual value is not a member of the set of permitted data values in the constrained value domain of a variable.The actual value is not a member of the set of permitted data values in the constrained value domain of a variable. (e.g., concept not provided by required code system).         |
| Negative infinity (NINF, nullflavor)      | negative infinity       | HL7        | C1550695 | Negative infinity of numbers.                                                                                                                                                                                                                                                                        |
| Positive infinity (PINF, nullflavor)      | positive infinity       | HL7        | C1550694 | Positive infinity of numbers.                                                                                                                                                                                                                                                                        |
| Un-encoded (UNC, nullflavor)              | un-encoded              | HL7        | C3242590 | The actual value has not yet been encoded within the approved value domain.                                                                                                                                                                                                                          |
| Masked (MSK, nullflavor)                  | masked                  | HL7        | C1555580 | There is information on this item available but it has not been provided by the sender due to security, privacy or other reasons. There may be an alternate mechanism for gaining access to this information.                                                                                        |
| Not applicable (NA, nullflavor)           | not applicable          | HL7        | C1272460 | Known to have no proper value (e.g., last menstrual period for a male).                                                                                                                                                                                                                              |
| Unknown (UNK, nullflavor)                 | unknown                 | HL7        | C1609613 | A proper value is applicable, but not known.                                                                                                                                                                                                                                                         |
| Asked but unknown (ASKU, nullflavor)      | asked but unknown       | HL7        | C1548672 | Information was sought but not found (e.g., patient was asked but didn't know)                                                                                                                                                                                                                       |
| Temporarily unavailable (NAV, nullflavor) | temporarily unavailable | HL7        | C1549057 | Information is not available at this time but it is expected that it will be available later.                                                                                                                                                                                                        |
| Not asked (NASK, nullflavor)              | not asked               | HL7        | C1548670 | This information has not been sought. (e.g., patient was not asked)                                                                                                                                                                                                                                  |
| Not available (NAVU, nullflavor)          | not available           | HL7        | C0686905 | Information is not available at this time (with no expectation regarding whether it will or will not be available in the future).                                                                                                                                                                    |
| Sufficient quantity (QS, nullflavor)      | sufficient quantity     | HL7        | C1699029 | The specific quantity is not known, but is known to be non-zero and is not specified because it makes up the bulk of the material. e.g. 'Add 10mg of ingredient X, 50mg of ingredient Y, and sufficient quantity of water to 100mL.' The null flavor would be used to express the quantity of water. |
| Trace (TRC, nullflavor)                   | trace                   | HL7        | C1552622 | The content is greater than zero, but too small to be quantified.                                                                                                                                                                                                                                    |

**Comment by aderidder** [comment]
What do you mean with "codes are represented by spaces"?

Are you planning to include the table itself as a value list? Or will you be using items from this table to add null-values to the "normal" value lists? 

As these are null-values they have to become "exception" tags in the xml. ART-DECOR actually validates this. I'm not sure whether it detects the "trace" or whether it detects "trc" or something else, but still it makes sense that these should be exceptions and not regular values.
Currently, the codesystem in my conversion software that will turn it into an exception tag is "NullFlavour", which is also known as codesystem 2.16.840.1.113883.5.1008. 
I could add "HL7" to also trigger this effect, but it doesn't have a codesystem id, since ART-DECOR doesn't already know it. So it's probably possible, but I'd have to look into it.

**Comment by gurnoor1990** [comment]
There are spaces in the codes
|Niveau/ Type|Code   |Weergavenaam           |Codesysteem|Omschrijving|
|------------|-------|-----------------------|-----------|------------|
|0-S         |NI     |NoInformation          |NullFlavor |            |
|1-S         |<br />INV   |invalid                |NullFlavor |            |
|2-L         |<br /><br />DER  |derived                |NullFlavor |            |
|2-S         |<br /><br />OTH  |other                  |NullFlavor |            |
|3-L         |<br /><br /><br />NINF|negative infinity      |NullFlavor |            |
|3-L         |<br /><br /><br />PINF|positive infinity      |NullFlavor |            |
|2-L         |<br /><br />UNC  |un-encoded             |NullFlavor |            |
|1-L         |<br />MSK   |masked                 |NullFlavor |            |
|1-L         |<br />NA    |not applicable         |NullFlavor |            |
|1-S         |<br />UNK   |unknown                |NullFlavor |            |
|2-S         |<br /><br />ASKU |asked but unknown      |NullFlavor |            |
|3-L         |<br /><br /><br />NAV |temporarily unavailable|NullFlavor |            |
|2-L         |<br />NASK |not asked              |NullFlavor |            |
|2-L         |<br />QS   |Sufficient Quantity    |NullFlavor |            |
|2-L         |<br />TRC  |trace                  |NullFlavor |            |
